name: CICULLIS (example)

on:
  pull_request:
    paths-ignore:
      - ".github/workflows/scorecard.yml"

permissions:
  contents: read

jobs:
  cicullis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: midiakiasat/cicullis@v1
